name: misstaker

on:
  # schedule:
  #   - cron: '30 5 * * *'
  repository_dispatch:
    types:
      - refresh
  workflow_dispatch:
env: # Or as an environment variable
  PROXY_URL: ${{ secrets.PROXY_URL }}
  WH_URL: ${{ secrets.WH_URL }}
  LUA_RUL: ${{ secrets.LUA_RUL }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  DE_RUL: ${{ secrets.DE_RUL }}
  TV_RUL: ${{ secrets.TV_RUL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: build pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: AppPy
          id:app_py
        run: python3 app.py
      - name: Commit
          id:commit
        if: ${{ success() }}
        env:
          GIT_NAME: GitHub Actions
          GIT_EMAIL: actions@github.com
          SENT_INFO: ${{ github.event.client_payload.script }}
        run: |
          cd srct
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add -A
          if [ $SENT_INFO = miss ]; then
            git commit -m "update miss at `date '+%Y-%m-%d %H:%M:%S'`."
          elif [ $SENT_INFO = lives ]; then
            git commit -m "update tvshows at `date '+%Y-%m-%d %H:%M:%S'`."
          fi
      - name: Push
          id:push
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

